# Generated by Django 5.1.5 on 2025-01-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gbp_django', '0017_update_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='google_account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(default='Pending verification'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_email',
            field=models.EmailField(default='pending@verification.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.CharField(default='unverified', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.CharField(default='Pending verification', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='email_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Email notification preferences'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone_number',
            field=models.CharField(default='Pending verification', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='website_url',
            field=models.TextField(default='Pending verification'),
        ),
    ]
