INSERT INTO gbp_django_business (
    business_name,
    business_id,
    business_email,
    address,
    phone_number,
    website_url,
    category,
    is_verified,
    is_connected,
    email_verification_pending,
    email_verification_token,
    email_settings,
    automation_status,
    qa_automation,
    posts_automation,
    reviews_automation,
    compliance_score,
    created_at,
    updated_at,
    user_id
) VALUES (
    'Test Business',
    'test-business-1',
    'test@example.com',
    '123 Test Street, Test City, TS 12345',
    '555-0123',
    'https://testbusiness.com',
    'Test Category',
    FALSE,
    TRUE,
    TRUE,
    'abc123token',
    '{"enabled":true,"compliance_alerts":true,"content_approval":true,"weekly_summary":true,"verification_reminders":true}',
    'Active',
    'manual',
    'manual',
    'manual',
    0,
    NOW(),
    NOW(),
    1
);
